# Generated by Django 5.2.2 on 2025-06-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_picture',
        ),
    ]
