<<<<<<< HEAD
=======
# Generated by Django 5.2.2 on 2025-06-08 23:59
>>>>>>> 4574bf8 (get all available doctors. handling related issues)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0001_initial'),
=======
        ('accounts', '0002_patient_disease_patient_medical_history_and_more'),
>>>>>>> 4574bf8 (get all available doctors. handling related issues)
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.doctor')),
            ],
        ),
    ]
