<<<<<<< HEAD
# Generated by Django 5.2.2 on 2025-06-09 22:40
=======
# Generated by Django 5.2.1 on 2025-06-09 21:05
>>>>>>> c9175f3d2baae1a26dec9eb2eb6d3da7fa93b687

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.doctor')),
            ],
        ),
    ]
