<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-06-10 20:48
=======
# Generated by Django 5.2.2 on 2025-06-10 14:51
>>>>>>> a911cb21a4bc8fd2e22a22d611b1675bdd979fb6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.doctor')),
            ],
        ),
    ]
